// source: point_cloud.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf')
var goog = jspb
var global = function () {
  if (this) {
    return this
  }
  if (typeof window !== 'undefined') {
    return window
  }
  if (typeof global !== 'undefined') {
    return global
  }
  if (typeof self !== 'undefined') {
    return self
  }
  return Function('return this')()
}.call(null)

goog.exportSymbol('proto.pointcloud.Point', null, global)
goog.exportSymbol('proto.pointcloud.PointCloudRequest', null, global)
goog.exportSymbol('proto.pointcloud.PointCloudResponse', null, global)
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pointcloud.Point = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.pointcloud.Point, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pointcloud.Point.displayName = 'proto.pointcloud.Point'
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pointcloud.PointCloudResponse = function (opt_data) {
  jspb.Message.initialize(
    this,
    opt_data,
    0,
    -1,
    proto.pointcloud.PointCloudResponse.repeatedFields_,
    null
  )
}
goog.inherits(proto.pointcloud.PointCloudResponse, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pointcloud.PointCloudResponse.displayName =
    'proto.pointcloud.PointCloudResponse'
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pointcloud.PointCloudRequest = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.pointcloud.PointCloudRequest, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pointcloud.PointCloudRequest.displayName =
    'proto.pointcloud.PointCloudRequest'
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.pointcloud.Point.prototype.toObject = function (opt_includeInstance) {
    return proto.pointcloud.Point.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.pointcloud.Point} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.pointcloud.Point.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        x: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
        y: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
        z: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pointcloud.Point}
 */
proto.pointcloud.Point.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.pointcloud.Point()
  return proto.pointcloud.Point.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pointcloud.Point} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pointcloud.Point}
 */
proto.pointcloud.Point.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {number} */ (reader.readDouble())
        msg.setX(value)
        break
      case 2:
        var value = /** @type {number} */ (reader.readDouble())
        msg.setY(value)
        break
      case 3:
        var value = /** @type {number} */ (reader.readDouble())
        msg.setZ(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pointcloud.Point.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.pointcloud.Point.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pointcloud.Point} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pointcloud.Point.serializeBinaryToWriter = function (message, writer) {
  var f = undefined
  f = message.getX()
  if (f !== 0.0) {
    writer.writeDouble(1, f)
  }
  f = message.getY()
  if (f !== 0.0) {
    writer.writeDouble(2, f)
  }
  f = message.getZ()
  if (f !== 0.0) {
    writer.writeDouble(3, f)
  }
}

/**
 * optional double x = 1;
 * @return {number}
 */
proto.pointcloud.Point.prototype.getX = function () {
  return /** @type {number} */ (
    jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0)
  )
}

/**
 * @param {number} value
 * @return {!proto.pointcloud.Point} returns this
 */
proto.pointcloud.Point.prototype.setX = function (value) {
  return jspb.Message.setProto3FloatField(this, 1, value)
}

/**
 * optional double y = 2;
 * @return {number}
 */
proto.pointcloud.Point.prototype.getY = function () {
  return /** @type {number} */ (
    jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0)
  )
}

/**
 * @param {number} value
 * @return {!proto.pointcloud.Point} returns this
 */
proto.pointcloud.Point.prototype.setY = function (value) {
  return jspb.Message.setProto3FloatField(this, 2, value)
}

/**
 * optional double z = 3;
 * @return {number}
 */
proto.pointcloud.Point.prototype.getZ = function () {
  return /** @type {number} */ (
    jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0)
  )
}

/**
 * @param {number} value
 * @return {!proto.pointcloud.Point} returns this
 */
proto.pointcloud.Point.prototype.setZ = function (value) {
  return jspb.Message.setProto3FloatField(this, 3, value)
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pointcloud.PointCloudResponse.repeatedFields_ = [1]

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.pointcloud.PointCloudResponse.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.pointcloud.PointCloudResponse.toObject(
      opt_includeInstance,
      this
    )
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.pointcloud.PointCloudResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.pointcloud.PointCloudResponse.toObject = function (
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        pointsList: jspb.Message.toObjectList(
          msg.getPointsList(),
          proto.pointcloud.Point.toObject,
          includeInstance
        ),
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pointcloud.PointCloudResponse}
 */
proto.pointcloud.PointCloudResponse.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.pointcloud.PointCloudResponse()
  return proto.pointcloud.PointCloudResponse.deserializeBinaryFromReader(
    msg,
    reader
  )
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pointcloud.PointCloudResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pointcloud.PointCloudResponse}
 */
proto.pointcloud.PointCloudResponse.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = new proto.pointcloud.Point()
        reader.readMessage(
          value,
          proto.pointcloud.Point.deserializeBinaryFromReader
        )
        msg.addPoints(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pointcloud.PointCloudResponse.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.pointcloud.PointCloudResponse.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pointcloud.PointCloudResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pointcloud.PointCloudResponse.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined
  f = message.getPointsList()
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.pointcloud.Point.serializeBinaryToWriter
    )
  }
}

/**
 * repeated Point points = 1;
 * @return {!Array<!proto.pointcloud.Point>}
 */
proto.pointcloud.PointCloudResponse.prototype.getPointsList = function () {
  return /** @type{!Array<!proto.pointcloud.Point>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.pointcloud.Point, 1)
  )
}

/**
 * @param {!Array<!proto.pointcloud.Point>} value
 * @return {!proto.pointcloud.PointCloudResponse} returns this
 */
proto.pointcloud.PointCloudResponse.prototype.setPointsList = function (value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value)
}

/**
 * @param {!proto.pointcloud.Point=} opt_value
 * @param {number=} opt_index
 * @return {!proto.pointcloud.Point}
 */
proto.pointcloud.PointCloudResponse.prototype.addPoints = function (
  opt_value,
  opt_index
) {
  return jspb.Message.addToRepeatedWrapperField(
    this,
    1,
    opt_value,
    proto.pointcloud.Point,
    opt_index
  )
}

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pointcloud.PointCloudResponse} returns this
 */
proto.pointcloud.PointCloudResponse.prototype.clearPointsList = function () {
  return this.setPointsList([])
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.pointcloud.PointCloudRequest.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.pointcloud.PointCloudRequest.toObject(
      opt_includeInstance,
      this
    )
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.pointcloud.PointCloudRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.pointcloud.PointCloudRequest.toObject = function (
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        filename: jspb.Message.getFieldWithDefault(msg, 1, ''),
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pointcloud.PointCloudRequest}
 */
proto.pointcloud.PointCloudRequest.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.pointcloud.PointCloudRequest()
  return proto.pointcloud.PointCloudRequest.deserializeBinaryFromReader(
    msg,
    reader
  )
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pointcloud.PointCloudRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pointcloud.PointCloudRequest}
 */
proto.pointcloud.PointCloudRequest.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString())
        msg.setFilename(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pointcloud.PointCloudRequest.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.pointcloud.PointCloudRequest.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pointcloud.PointCloudRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pointcloud.PointCloudRequest.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined
  f = message.getFilename()
  if (f.length > 0) {
    writer.writeString(1, f)
  }
}

/**
 * optional string filename = 1;
 * @return {string}
 */
proto.pointcloud.PointCloudRequest.prototype.getFilename = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ''))
}

/**
 * @param {string} value
 * @return {!proto.pointcloud.PointCloudRequest} returns this
 */
proto.pointcloud.PointCloudRequest.prototype.setFilename = function (value) {
  return jspb.Message.setProto3StringField(this, 1, value)
}

goog.object.extend(exports, proto.pointcloud)
