/**
 * @fileoverview gRPC-Web generated client stub for simplegrpc
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.19.1
// source: simple_grpc.proto

/* eslint-disable */
// @ts-nocheck

const grpc = {}
grpc.web = require('grpc-web')

const proto = {}
proto.simplegrpc = require('./simple_grpc_pb.js')

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.simplegrpc.SimpleGrpcClient = function (hostname, credentials, options) {
  if (!options) options = {}
  options.format = 'text'

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options)

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '')
}

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.simplegrpc.SimpleGrpcPromiseClient = function (
  hostname,
  credentials,
  options
) {
  if (!options) options = {}
  options.format = 'text'

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options)

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '')
}

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.simplegrpc.HelloReq,
 *   !proto.simplegrpc.HelloRes>}
 */
const methodDescriptor_SimpleGrpc_SayHello = new grpc.web.MethodDescriptor(
  '/simplegrpc.SimpleGrpc/SayHello',
  grpc.web.MethodType.UNARY,
  proto.simplegrpc.HelloReq,
  proto.simplegrpc.HelloRes,
  /**
   * @param {!proto.simplegrpc.HelloReq} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary()
  },
  proto.simplegrpc.HelloRes.deserializeBinary
)

/**
 * @param {!proto.simplegrpc.HelloReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.simplegrpc.HelloRes)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.simplegrpc.HelloRes>|undefined}
 *     The XHR Node Readable Stream
 */
proto.simplegrpc.SimpleGrpcClient.prototype.sayHello = function (
  request,
  metadata,
  callback
) {
  return this.client_.rpcCall(
    this.hostname_ + '/simplegrpc.SimpleGrpc/SayHello',
    request,
    metadata || {},
    methodDescriptor_SimpleGrpc_SayHello,
    callback
  )
}

/**
 * @param {!proto.simplegrpc.HelloReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.simplegrpc.HelloRes>}
 *     Promise that resolves to the response
 */
proto.simplegrpc.SimpleGrpcPromiseClient.prototype.sayHello = function (
  request,
  metadata
) {
  return this.client_.unaryCall(
    this.hostname_ + '/simplegrpc.SimpleGrpc/SayHello',
    request,
    metadata || {},
    methodDescriptor_SimpleGrpc_SayHello
  )
}

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.simplegrpc.HelloReq,
 *   !proto.simplegrpc.HelloRes>}
 */
const methodDescriptor_SimpleGrpc_CheckInbox = new grpc.web.MethodDescriptor(
  '/simplegrpc.SimpleGrpc/CheckInbox',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.simplegrpc.HelloReq,
  proto.simplegrpc.HelloRes,
  /**
   * @param {!proto.simplegrpc.HelloReq} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary()
  },
  proto.simplegrpc.HelloRes.deserializeBinary
)

/**
 * @param {!proto.simplegrpc.HelloReq} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.simplegrpc.HelloRes>}
 *     The XHR Node Readable Stream
 */
proto.simplegrpc.SimpleGrpcClient.prototype.checkInbox = function (
  request,
  metadata
) {
  return this.client_.serverStreaming(
    this.hostname_ + '/simplegrpc.SimpleGrpc/CheckInbox',
    request,
    metadata || {},
    methodDescriptor_SimpleGrpc_CheckInbox
  )
}

/**
 * @param {!proto.simplegrpc.HelloReq} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.simplegrpc.HelloRes>}
 *     The XHR Node Readable Stream
 */
proto.simplegrpc.SimpleGrpcPromiseClient.prototype.checkInbox = function (
  request,
  metadata
) {
  return this.client_.serverStreaming(
    this.hostname_ + '/simplegrpc.SimpleGrpc/CheckInbox',
    request,
    metadata || {},
    methodDescriptor_SimpleGrpc_CheckInbox
  )
}

module.exports = proto.simplegrpc
