# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import point_cloud_pb2 as point__cloud__pb2


class PointCloudStreamServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStreamPointCloud = channel.unary_stream(
                '/pointcloud.png.PointCloudStreamService/GetStreamPointCloud',
                request_serializer=point__cloud__pb2.PointCloudRequest.SerializeToString,
                response_deserializer=point__cloud__pb2.PointCloudResponse.FromString,
                )


class PointCloudStreamServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStreamPointCloud(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PointCloudStreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStreamPointCloud': grpc.unary_stream_rpc_method_handler(
                    servicer.GetStreamPointCloud,
                    request_deserializer=point__cloud__pb2.PointCloudRequest.FromString,
                    response_serializer=point__cloud__pb2.PointCloudResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pointcloud.png.PointCloudStreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PointCloudStreamService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStreamPointCloud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/pointcloud.png.PointCloudStreamService/GetStreamPointCloud',
            point__cloud__pb2.PointCloudRequest.SerializeToString,
            point__cloud__pb2.PointCloudResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
